version: "3.8"


services:
  react-app:
     build: .
     container_name: container_one
     ports:
       - "3000:3000"
     environment:
       - NODE_ENV=development
     networks:
       - app_network
    
networks:
  app_network:
    driver: bridge
