apiVersion: v1
kind: Namespace
metadata:
  name: jobby-app
---

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: jobby-app
  name: jobby-deplyment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: jobby
  template:
    metadata:
      labels:
        app: jobby
    spec:
      containers:
      - name: jobby-container
        image: pranay801/jobby:latest
        ports:
        - containerPort: 3000
        resources:
          requests:
            memory: "200Mi"
            cpu: "200m"
          limits:
            memory: "500Mi"
            cpu: "500m"
---

apiVersion: v1
kind: Service
metadata:
  name: jobby-svc
  namespace: jobby-app
spec:
  selector:
    app: jobby
  ports:
  - port: 80
    targetPort: 3000
---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: jobby-app
  name: jobby-ing
  labels:
    name: jobby-ing
spec:
  ingressClassName: nginx
  rules:
  - host: jobby.com
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: jobby-svc
            port:
              number: 80

